
public class TryCatchException {

	public static void main(String[] args) {
		int i=9;
		int j = 0;
		int arr[] = new int[6];
		arr[6] = 8;
		
		try {
			int k = i/j;
		}
		catch(ArithmeticException e)
		{
			System.err.println("ERROR: ");
		}
		finally
		{
			System.out.println("Will be printed irrespective of exception occur or not");
		}

	}

}
